# Clothing {#clothing}

In this video we are going to discuss clothing. 

Let me start by answering something I've been asked many times: you cannot have the recording hanging from a string, or in a pouch, or in a pocket. All such recordings will have noise that will make automated analyses impossible. Your only option is to have the recording worn 10-20cm away from the child's mouth, as stable as possible with respect to the child themself. This means one of two things: either in a custom-sized or adapted pocket, or clipped to the child's outermost layer of clothing. We speak about each in turn.

## Custom-sized pockets

### LENA t-shirts

If you are planning to use the LENA device, you are probably going to buy the clothes they are selling, usually t-shirts. These t-shirts are excellent, like the device, but like the device they are also quite pricey (25 US$ per unit). If you have chosen babyloggers, we also recommend LENA clothing -- we explain why in a moment.

If you don’t buy LENA t-shirts, you have a few other options.

### Non-LENA t-shirts

First, you can try and replicate what LENA decided, meaning having t-shirts with a pocket sewed on them. In our experience, buying 100% cotton t-shirts and having pockets sewn on them is going to cost you more or less the same as buying LENA t-shirts, with a lot more hassle, since you need to find someone for the sewing, send them a prototype, etc. If you are using LENA or Babylogger as your device, then you're probably better off buying t-shirts from LENA. 

However, you may have no choice than custom-made clothing. This may happen because you work in conditions where t-shirts are not ideal - perhaps it is too cold, with children outside most of the time wearing several other layers of clothing, in which case the recording will be muffled. Or if you have chosen a wireless system, one or two USBs, or a hand-held recorder -- all of these devices require pockets that are a different size from LENA's device (and pocket). 

In this case what we suggest is that you make pockets where the device can fit perfectly snuggly, so that it doesn’t move while recording and this avoids recording too much noise. The pocket must be really very, very tight, so that there is absolutely no friction between the clothing and the recording device. Additionally, the t-shirt itself should be tight against the child's body, and not hanging loose.

Second, you can buy a t-shirt that already has a pocket, even if the pocket is not the right size, as long as you stuff something in so that the device itself doesn't move. You can use fabric, or cotton -- whatever you use, just consider that the family should be able to retrieve the device to turn it off and put it back in after turning it on, without causing bad quality data (e.g., by putting the stuffing on top of the device rather than behind it). Also, ask yourself whether the stuffing may present any kind of hazard to the child.

#### How to close the pocket

When having the t-shirt made, ask the sewing person to sew a pressure button on the pocket, like the ones LENA t-shirts have. This person will probably complain about this because they are hard to make if you do them by hand. But there is really no alternative to these pressure buttons because they are both childproof and easy to use by parents/researchers, plus they make sure the device doesn’t fall off. 

One alternative we used in the past is velcro strips. These are fine if you work in an urban setting, which is very clean. In the past we used them in a field setting and we were not happy with them. The more you wash them, the less adhesive they become. 

The last option you have for closing the pocket is a regular button with a button hole. You should think carefully before pursuing this, because if the children you are going to work with are a certain age (old enough to play with the button, but young enough to not realize the risk), small buttons can be a choking hazard. 

## Alternatives to t-shirts

These options might still not be good for you, either because they are too costly or because t-shirts or vests are not a good clothing solution.

### Vests

For example, if you are going to work with populations where t-shirts are just the lowest layer (because they live in cold places), then t-shirts are simply not a good idea, because there are always going to be more clothes on top of the recorder and this causes noise and muffled sound. 

An excellent alternative are vests. LENA does not sell them anymore, but you can ask around and see if someone still has them because they are really terrific: the child can wear them as inner or outer layers of clothing, so they can be a good solution both for places that are very hot or very cold. This will probably mean that you need to custom-design a vest, and a pocket.

If you don’t find anybody who can sew pockets on your t-shirts, or if you cannot afford to buy regular t-shirts with pockets you might want to consider this alternative. 

### Harness

A possibility is that you create a system of straps that kind of looks like a harness (or a bra). One researcher that uses them is Marisa Casillas, so you can check her paper in the resources section, where she has a picture of this: it has a pocket on the front where you can put the device. Yyou can make the straps elastic, which will allow you to fit children of different ages. It can be used in very warm and very cold climates.

### Attaching the device to a piece of clothing

Another option is to buy a money clip or a very large paper clip, so that you can clip the device on the child’s t-shirt or sweater. If you do that, remember to check whether there is something that might cause a choking hazard: the clip needs always to be childproof and child friendly. Remember also that families need to access the on/off button to make use of their right to withdrawal.

## Final comments

I've already said this but I cannot repeat this enough: To ensure the best quality audio,

1. Try to use clothing where the device is completely stable (tight-fitting clothing, device firmly attached): you want to avoid noises from clothes rustling as much as possible;
2. Place the recorder in the outermost layer of clothing possible to avoid muffled sounds.

## Resources

- LENA t-shirts: LENA no longer has a section where you can view their products. You should approach them for a quote via [the LENA contact form](https://www.lena.org/contact/)
- Custom pockets: We don't yet have a publication for this, but we hope to -- soon!
- Harness-like: Casillas, Marisa, Penelope Brown, and Stephen C. Levinson. "Early language experience in a Tseltal Mayan village." Child Development 91.5 (2020): 1819-1835. [pdf](https://pure.mpg.de/rest/items/item_3184321_3/component/file_3184322/content?download=true)
