# Logistics {#logistics}

In this video we are going to talk about logistics, including how many devices you need for your research and how to organize your data collection. We are going to focus on an urban setting because field conditions are discussed in another video (see Video \@ref(field)). 



## How to deliver the hardware

Many researchers in the past would go to the family's home at the beginning of the day, to fit the child with the device and turn it on, then picked up the device at the end of the day, so that the parents didn’t need to do anything particular. I think that today, whether you are using LENA or another device, you don’t need to drop off and pick up the equipment yourself. There are downsides to doing the drop-off and pick-up yourself in the same day of recording, including that your presence is very salient to the child and the people around them, and also that you are not capturing interactions early in the morning and late in the day. 

You can instead mail the device and clothing to the families or use a courrier service. Even if you decide to visit the family, you can explain to them how to turn the recording on and off -- which they need to know anyone to apply their right of withdrawal (i.e., to not have certain sections of the day recorded). Another option that may be good for you depending on your community contact is to have devices and clothing delivered to a trusted center, like a daycare or a clinic -- provided that you can make sure that nobody will tamper with the recordings and that the devices will be kept in a secure location. 

In the hardware section, we explained that the only device for which you have time stamps with respect to local time is LENA. So if you are using a different device, you should ask parents to speak into the device, after it has been turned off, what time it is then. This will allow you to track the time and position the recording with respect to time of day. You can ask them to again say the time into the device if they pause it. Please note that some devices do not start recording immediately -- so to be on the safe side, ask the family to count to five before saying the time and day (i.e. say "one two three four five -- today is Wednesday August 3 2021 and the time is 09:25am").

## How long to record for

We recommend recording for the maximum storage duration whenever possible, because we have some initial evidence that derived metrics are more reliable the more  recordings you have, perhaps because with more data are a better representation of what the child’s environment is like.  (We also have some evidence that recordings about 4h in length or shorter have a lot more speech than longer ones -- probably because the family is overly conscious -- so try to record at least 6h continuously, without asking the family to interact with the recordings again.)

If you are using the newest generation of LENA, that means you can record up to 72 hours total, asking families to recharge the device overnight. Similarly for the USBs, which can often hold 150 hours total; and the Babylogger, which can hold even more. 

That said, most researchers are only recording one full day, and as we will see below, instructions to parents do get more complicated the more you ask them to do, so think deeply about how much data you truly need.

## How to communicate about the hardware with family members

We have found it useful to provide parents with both oral and written instructions on everything they need to know: how the device works, how to turn it on, how they need to attach it to the clothing, how to recharge it (if you are recording multiple days), and that they can just go about their day. The written version could be provided printed out as well as on a website. This is useful because you can also have FAQs at the end, which will be composed by the things that the representatives of the community told you during your piloting sessions (see Video \@ref(pilot). This may be how the data are going to be analysed, how they are going to be used for, etc. So anything parents told you or asked you about in the piloting stage, you can have it in a little booklet. 

The booklet is useful to some parents who like to consult it and have everything written down. However, for some things, it may be better to have short videos that are accessible through a QR code that the parents can scan in the booklet. This way, they can read the explanation or watch the video. Particularly, regarding how to put the device in clothing, the booklet has pictures but nothing really replaces a tutorial video, so if you can do that, it will probably be appreciated. 

Ideally, you should also have a phone number they can call or send a message to, for instance via WhatsApp, if that is common in the community you are working with. This is very reassuring in case they have questions that are not in the booklet, or they want to refer someone else to you, for instance because they were incidentally recorded.

## How many devices do you need?

This does not only depend in the number of families you are recording, but crucially on the logistics, and how devices get dropped off and picked up. Let us start assuming that you visit the home for drop-off and pick-up.

So from the time you drop the equipment to the moment you pick it up, it is minimally going to take 3 days, because you will drop the device the day before they record and you’ll pick it up the day after. Also, we noticed that it’s not always easy for parents to launch the recording, and also, depending on your design, you might want to pick one week day and one weekend day, so in this case you might assume that one device is going to stay with the family for one whole week. 

Next, let us assume that you mail the devices, and have parents mail them back. In our experience, you should count a whole week on each side of the recording, because it is hard for parents to remember to mail it back, and the mail service takes some time.

In addition to the time of the recording and the delays of transferring the devices between your institution and the family, you also want to consider the time it takes to repurpose the device and clothing. Extracting the data takes only a few minutes, but whoever does this needs to make sure to be very careful in assigning recordings to individuals, since an error at this point is hard to undo. In addition, you need to recharge the devices, which takes about 2h for any of them. If you are using t-shirts or other such clothing, you should also budget time for washing them. 

### Sample calculation 1

So, for instance, imagine you want to launch a study where you have 40 families participating and you want each family to contribute with one set of recordings per month from the ages of 6 months to the age of 12 months of the child. So in this case you will need at least 30 recording devices and 30 sets of t-shirts. This is because: imagine you have device 1 that goes with family 1 on week number 1. Then, you can use it with another family but probably it’s a little bit risky to use it on week number 2 so you will use it with family 2 on week number 3. This is because otherwise you would need to pick up the device, wash the t-shirts and drop the equipment off to the next family on the same day. 
(People who have been doing this in a large scale had cases in which a device got thrown in the toilet or it got crashed or the child jumped into a pool with the device on, so one should plan for at least one or two devices getting lost or broken).

### Sample calculation 2


- 500 families, recorded twice, one year apart (pre- and post-intervention)
- study rolled out seeing 50 families in a given week

**2.a. Assuming drop-off and pick-up through in-person visits to the homes**: Given potential equipment loss and to reduce logistic burden, 60 recording units should be purchased (50/week + 10 extra).

**2.b. Assuming drop-off and pick-up through mail** (7 days to send out & get back the recorders): Given potential equipment loss and to reduce logistic burden, 160 recording units should be purchased (50/week x 3 weeks given delays in mailing in/out equipment, 10 extra).

### Sample calculation 3

- 50 families, recorded once a week (8h), for 3 months
- study rolled out by recruiting five families per month

That means that at the "peak" of data collection, 15 families are recording the same week. Families keep the equipment over the 3 months of data collection, so drop-off & pick-up happen only once per family.

**3.a. Assuming drop-off and pick-up through in-person visits to the homes**: Given potential equipment loss and to reduce logistic burden, 60 recording units should be purchased 20 recording units should be purchased (15/week + 5 extra).

**3.b. Assuming drop-off and pick-up through mail** (7 days to send out & get back the recorders): Given potential equipment loss and to reduce logistic burden, 30 recording units should be purchased (10/week + (5/week equipment that is changing families) x 3 weeks given delays in mailing in/out equipment, 5 extra).


## Resources

- [ExELang cost analyses](https://docs.google.com/document/d/1qzY871lnUbD1nGsBcUoFoipwBgbXRCcUeaNI0sfIBWw/edit)
- [Example information for parents (French)](https://osf.io/4grsn/)


