# Tutorial of our ChildProject software {#childproject}

The ChildProject package is one part of a three-part solution to the difficulties faced when working with long-form recordings. The other two parts are Datalad and git-annex, which we do not detail here.

ChildProject is a package to manage daylong recordings. It is written in python, but it can also be used from the command line so that no knowledge of python required. We have defined standards regarding the structure of the data, which we explained in previous videos. The package helps enforce these standards with tests. It also provides tools to convert annotations from a variety of input formats (LENA, ELAN, Praat, ALICE/VTC, etc.) And, it has m
ore functionalities : batch audio conversion, sampling, eaf generation, ITS anonymization, etc.


## Resources

[ChildProject documentation on datasets structure](https://childproject.readthedocs.io/en/latest/format.html)

Gautheron, L., Rochat, N., & Cristia, A. (2021). Managing, storing, and sharing long-form recordings and their annotations. [pdf](https://psyarxiv.com/w8trm/download?format=pdf)
